name: vectology-stage2

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  # dev
  - black
  - isort
  - autoflake
  - flake8
  - jupyterlab
  - nodejs
  - mypy
  # rest
  - pydash
  - loguru
  - icecream
  - numpy
  - pandas
  - seaborn
  - nltk
  - gensim
  - pip
  - pip:
    - nb_black
    - nxontology
    - scispacy
    - spacy
