name: Vectology

channels:
  - anaconda
  - conda-forge

dependencies:
  - python=3.7
  - black
  - beautifulsoup4
  - elasticsearch
  - matplotlib
  - numpy
  - pandas
  - scipy
  - requests
  - networkx
  - jupyter
  - jupyterlab
  - scikit-bio
  - seaborn
  - pandas-profiling==2.10.1
  - pip:
    - nxontology
    - ontoma
